import { sendRichHtml } from '../../lib/richhtml.js'

const html = `<style>*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;user-select:none}body{margin:0;background:#0d0c16;color:#fff;font-family:Arial}.card{max-width:540px;margin:auto;padding:16px;border-radius:22px;background:radial-gradient(circle at top right,#4b3e81,#171424 62%,#0d0c16);border:1px solid #7766c5;box-shadow:0 14px 38px #0009}.small{font-size:9px;letter-spacing:2px;color:#bbb2dd}.title{font-size:22px;font-weight:900;margin:4px 0 14px}.display{min-height:70px;padding:12px;border-radius:14px;background:#09090e;border:1px solid #5f5292;text-align:right;word-break:break-all}.expr{font-size:12px;color:#aaa2c8;min-height:18px}.result{font-size:27px;font-weight:900;margin-top:5px;color:#f4f2ff}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.key{height:48px;border:0;border-radius:12px;background:#ffffff16;color:#fff;font-size:17px;font-weight:bold;box-shadow:inset 0 1px #ffffff16}.key:active{transform:scale(.95);background:#8c79e5}.op{background:#6654b6}.danger{background:#9b424d}.equals{background:#39a875}</style><div class="card"><div class="small">ELITE-PRO-V2 TOOLS</div><div class="title">Calculator</div><div class="display"><div class="expr" id="expr">0</div><div class="result" id="result">0</div></div><div class="keys" id="keys"><button class="key danger" data-v="C">C</button><button class="key" data-v="(">(</button><button class="key" data-v=")">)</button><button class="key op" data-v="/">÷</button><button class="key" data-v="7">7</button><button class="key" data-v="8">8</button><button class="key" data-v="9">9</button><button class="key op" data-v="*">×</button><button class="key" data-v="4">4</button><button class="key" data-v="5">5</button><button class="key" data-v="6">6</button><button class="key op" data-v="-">−</button><button class="key" data-v="1">1</button><button class="key" data-v="2">2</button><button class="key" data-v="3">3</button><button class="key op" data-v="+">+</button><button class="key" data-v="0">0</button><button class="key" data-v=".">.</button><button class="key" data-v="DEL">⌫</button><button class="key equals" data-v="=">=</button></div></div><script>let e='';const ex=document.getElementById('expr'),r=document.getElementById('result');function paint(){ex.textContent=e||'0'}function solve(){if(!/^[0-9+*/(). -]+$/.test(e))return;r.textContent=Function('return ('+e+')')();}document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{let v=b.dataset.v;if(v==='C'){e='';r.textContent='0'}else if(v==='DEL')e=e.slice(0,-1);else if(v==='='){try{solve()}catch{r.textContent='Error'}}else e+=v;paint()});document.addEventListener('keydown',a=>{if(/[0-9+*/().-]/.test(a.key)){e+=a.key;paint()}if(a.key==='Enter')try{solve()}catch{r.textContent='Error'}if(a.key==='Backspace'){e=e.slice(0,-1);paint()}})</script>`

let handler = async (m, { EliteProTech }) => {
    try {
        await sendRichHtml(EliteProTech, m.chat, { id: 'elite-calculator', title: 'ELITE-PRO-V2 • CALCULATOR', html, source: 'eliteprotech' })
    } catch (error) {
        await m.reply(`Unable to send calculator: ${error.message || String(error)}`)
    }
}

handler.command = ['calculator', 'calc']

export default handler
